djangoExercises/firstProject/firstProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapplication.urls')),
]

djangoExercises/firstProject/firstapplication/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
]

djangoExercises/firstProject/firstapplication/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.
class Name(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.ForeignKey(Name, on_delete=models.CASCADE)
    contact = models.CharField(max_length=15)
    

    def __str__(self):
        return self.contact


class Address(models.Model):
    name = models.ForeignKey(Name, on_delete=models.CASCADE)
    address = models.CharField(max_length=30)
    

    def __str__(self):
        return self.address

djangoExercises/firstProject/firstapplication/views.py
from django.shortcuts import render
from .models import Name
# Create your views here.
def home(request):
    objs = Name.objects.all
    context = {'people' : objs}
    return render(request, 'firstapplication/home.html', context)    

djangoExercises/firstProject/firstapplication/templates/firstapplication/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <h1>Hi! Welcome</h1>
    {% block head %} {% endblock %}
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

djangoExercises/firstProject/firstapplication/templates/firstapplication/home.html
{% extends 'firstapplication/base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'firstapplication/home.css' %}" />

{% endblock %} {% block content %}
<div class="container">
  <h5>This is a list of dummy data I created in the shell</h5>
</div>
<div class="container">
  <table>
    <tr>
      <th>Name</th>
      <th>Contact</th>
      <th>Address</th>
    </tr>
    {% for person in people %}
    <tr>
      <td>{{ person }}</td>
      <td>{{ person.contact_set.first }}</td>
      <td>{{ person.address_set.first }}</td>
    </tr>
    {% endfor %}
  </table>
</div>
<div class='container bird'>
  <img src="{% static 'firstapplication/bird.jpeg' %}" ></img>
</div>

{% endblock %}
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
  crossorigin="anonymous"
></script>